
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DICE_MOVE LADDER_MOVE NUMBER PLAYER SNAKE_MOVE TOgame : statementsstatements : statement\n                  | statements statementstatement : PLAYER movemove : DICE_MOVE NUMBERmove : SNAKE_MOVE NUMBER TO NUMBERmove : LADDER_MOVE NUMBER TO NUMBER'
    
_lr_action_items = {'PLAYER':([0,2,3,5,6,10,15,16,],[4,4,-2,-3,-4,-5,-6,-7,]),'$end':([1,2,3,5,6,10,15,16,],[0,-1,-2,-3,-4,-5,-6,-7,]),'DICE_MOVE':([4,],[7,]),'SNAKE_MOVE':([4,],[8,]),'LADDER_MOVE':([4,],[9,]),'NUMBER':([7,8,9,13,14,],[10,11,12,15,16,]),'TO':([11,12,],[13,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'game':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,5,]),'move':([4,],[6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> game","S'",1,None,None,None),
  ('game -> statements','game',1,'p_game','_parser.py',33),
  ('statements -> statement','statements',1,'p_statements','_parser.py',37),
  ('statements -> statements statement','statements',2,'p_statements','_parser.py',38),
  ('statement -> PLAYER move','statement',2,'p_statement','_parser.py',41),
  ('move -> DICE_MOVE NUMBER','move',2,'p_move_dice','_parser.py',44),
  ('move -> SNAKE_MOVE NUMBER TO NUMBER','move',4,'p_move_snake','_parser.py',47),
  ('move -> LADDER_MOVE NUMBER TO NUMBER','move',4,'p_move_ladder','_parser.py',50),
]
